<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>

var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员信息"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"教师管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"教师管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"停车区域管理",
			            "menuJump":"列表",
			            "tableName":"tingchequyu"
			        }
			    ],
			    "menu":"停车区域管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"车位信息管理",
			            "menuJump":"列表",
			            "tableName":"chewei"
			        }
			    ],
			    "menu":"车位信息管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"车位预约管理",
                        "menuJump":"列表",
                        "tableName":"yuyue"
                    }
                ],
                "menu":"车位预约管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "删除"
			            ],
			            "menu":"停车信息管理",
			            "menuJump":"列表",
			            "tableName":"tingche"
			        }
			    ],
			    "menu":"停车信息管理"
			} 
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"新闻类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryNews"
                    }

                ],
                "menu":"新闻类型管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"新闻管理",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"新闻管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
	    "backMenu":[
	        {
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "预约"
			            ],
			            "menu":"停车区域管理",
			            "menuJump":"列表",
			            "tableName":"tingchequyu"
			        }
			    ],
			    "menu":"停车区域管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"车位信息管理",
			            "menuJump":"列表",
			            "tableName":"chewei"
			        }
			    ],
			    "menu":"车位信息管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "审核"
	                    ],
	                    "menu":"车位预约管理",
	                    "menuJump":"列表",
	                    "tableName":"yuyue"
	                }
	            ],
	            "menu":"车位预约管理"
	        }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "离校",
			                "修改"
			            ],
			            "menu":"停车信息管理",
			            "menuJump":"列表",
			            "tableName":"tingche"
			        }
			    ],
			    "menu":"停车信息管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"新闻管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"新闻管理"
	        }
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"教师",
	    "tableName":"yonghu"
	}
];

var hasMessage = '';
